### ISSUE TITLE
Lay Out Taxonomy Page

### ISSUE THREAD

**Issue by edutrul** [bugguide/bugguide#11]
Create the layout for the taxonomy page.

Example:
- http://bugguide.net/node/view/173/tree
- https://beta.bugguide.net/node/173/tree

### Comments

From Sarah:
I wlll provide an HTML wireframe soon.
I also found that the classification tree on the Info tab is made with spans and nbsp's https://beta.bugguide.net/node/173, which we should see if we can get into a ul
John, here is the ul HTML on my Christmas list: http://codepen.io/biology-it/pen/YZaErg

From Juampy:
Sarah Carney, did the codepen expire?

![image](https://user-images.githubusercontent.com/1582129/96153093-e56d5200-0ed2-11eb-8040-d8266ab2f398.png)

I probably deleted it. This was super early work from last year and we didn't end up actually templating a taxonomy page. I'll need to start from scratch here, too.

**Comment by kleintom** [comment]
I think this is done; the taxonomy page has an indented tree.
