### ISSUE TITLE
Links tab should be chosen when viewing individual link

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#139]
*   the full tabs are shown across the top; should be like when viewing Image; the Links tab should be selected when viewing and individual Link

![](https://user-images.githubusercontent.com/456917/101357506-23e21600-385f-11eb-8dfc-2ef8104ce255.png)

To see how to do this for Links, see https://github.com/bugguide/bugguide/blob/ce3acfab998fd246d1811d7eb66865c0a4c4214e/sites/all/modules/custom/bg/bg.module#L330

**Comment by kleintom** [comment]
Oops, I opened #198 as a dup of this; I think it can be closed by #202

**Comment by clouseau** [comment]
Confirmed. Closing.
