### ISSUE TITLE
Parent field should not be shown on Links

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#141]
The parent field should not be displayed when viewing an individual Link content type.

Like other fields, the parent field should also be hidden on edit. See how bgpage does this: https://github.com/bugguide/bugguide/blob/ce3acfab998fd246d1811d7eb66865c0a4c4214e/sites/all/modules/custom/bgpage/bgpage.module#L245

**Comment by kleintom** [comment]
I have prs for both issues, but as far as I can tell the only way to submit a link right now is to enter the parent manually, so I'll hold off on submitting this one for now (we could check and only not show the parent field on edit for now, but I think eventually we won't want to show the parent field on creation either).

**Comment by kleintom** [comment]
Verified as fixed on beta, this issue can be closed.
