### ISSUE TITLE
Add button is missing from Books and Links

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#144]
Authenticated users may add Image, Books and Links. On Images, this is easy. Go to any taxon, click the Images tab, and wow, a nice button!

![](https://user-images.githubusercontent.com/456917/101808903-87c54280-3adc-11eb-9249-c92e73800df5.png)

Sadly, clicking on the Books tab does not show an Add book button and clicking on the Links tab does not show an Add Link button.

**Comment by kleintom** [comment]
Looks like this is working now for me on beta, I think this can be closed.
