### ISSUE TITLE
Taxonomy tree layout breaks halfway through

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#159]
Related to #11 perhaps.

Go to http://bugguide.test/node/55/tree and then click the Expand Tree button. Formatting breaks:

![](https://user-images.githubusercontent.com/456917/102624452-a72a2400-4109-11eb-812d-6b2cd9bd970d.png)

**Comment by kleintom** [comment]
Here's a shorter taxonomy tree that shows the bug but loads significantly faster: https://beta.bugguide.net/node/112/tree?expand

**Comment by kleintom** [comment]
If I load that last link in firefox, load the source view, and then hover my mouse over the first incorrectly layed out line - which shows up in red in firefox - I see this:
![image](https://user-images.githubusercontent.com/632915/140593950-35b98f20-dbfa-49b6-841a-7a403509ea29.png)
'The document tree is too deep. The tree will be flattened to 513 elements deep.'
(As a separate issue, also note that the `</br>` shows up in red.)

**Comment by kleintom** [comment]
Working on beta now, even node 3 (well, not that I checked every indentation).
