### ISSUE TITLE
Link thumbnails in advanced search view

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#165]
The Content: Image field on the Advanced Search view [https://beta.bugguide.net/admin/structure/views/view/advanced_search/edit/page](https://beta.bugguide.net/admin/structure/views/view/advanced_search/edit/page) should link to content.

E.g, in [https://beta.bugguide.net/advanced-search?taxon=4018](https://beta.bugguide.net/advanced-search?taxon=4018) the first column should be linked to content.

The feature that provides this view in bgimage.views.default.inc will need to be updated to reflect the change.

**Comment by kleintom** [comment]
Verified as fixed in beta, this can be closed.
