### ISSUE TITLE
Breadcrumbs cannot be copied to clipboard

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#171]
Navigate to an image.

Try to copy the taxonomic breadcrumb trail. You can't. Tried in Firefox 89 and Chrome 91.

(Submitted by Emile at https://bugguide.net/node/view/180481#3266970 )

**Comment by kleintom** [comment]
Breadcrumbs can now be copied (if you copy more than one crumb the copy inserts newlines between crumbs).
