### ISSUE TITLE
Arrow keys for next/previous page  

### ISSUE THREAD

**Issue by jbschnei** [bugguide/bugguide#181]
It would be nice if, in Beta, you could navigate to the next or previous page by using the arrow keys, as you can in the current version.

**Comment by clouseau** [comment]
The task here is to integrate the existing JS with paged results:

```
<script>
  document.addEventListener('keyup', function(e) {
    // ignore modifier keys
    if (e.altKey || e.shiftKey || e.ctrlKey || e.metaKey) return;
  	if(e.which == 37) {
  		document.querySelector(".pager>div:nth-child(2)>a").click();
  	} else if(e.which == 39) {
  		document.querySelector(".pager>div:nth-child(4)>a").click();
  	}
  }); 
</script>
```

**Comment by kleintom** [comment]
Looks like this is working on beta, I think this issue can be closed.

**Comment by kleintom** [comment]
Looks like this is working on any page that shows a pager:
![image](https://user-images.githubusercontent.com/632915/146650351-3b693a96-8fb5-46a9-9955-1808bca794cd.png)
