### ISSUE TITLE
Include the full species name in the description?

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#184]
In https://beta.bugguide.net/node/924810 for example the description under the image is "Unknown Buprestid – cyanescens", which in current bugguide would be "Unknown Buprestid - _Agrilus cyanescens_": the full species name, and italicized.  (This would also help with giving a place to highlight/copy the full species name from, which I think was an issue mentioned elsewhere (the links at the top being uncopyable).)

**Comment by kleintom** [comment]
As far as I know there's quite a bit more to this than the current implementation at https://github.com/bugguide/bugguide/blob/748088e8d33f0be425312c0f3bfa62ec65447d4b/sites/all/modules/custom/bgimage/bgimage.ds.field.inc#L81
Things like dealing with No Taxon nodes, subspecies, not displaying a dash or classification above genus level, not displaying the user's title if it matches the classification title, probably some other things I'm missing. I think I can write all of that if we need to, but I'm wondering if it would be easier/better to just start with the current BugGuide implementation and adjust it for D7; I would think most of the logic would stay the same?

**Comment by kleintom** [comment]
Hmm, looks like at least some of that is already implemented for the breadcrumbs, I'll look around some more.

**Comment by kleintom** [comment]
Breadcrumbs deals with some of the issues, but I'd still prefer to see the current title logic, if that's possible; otherwise I can probably guess most of it.  A related question for testing: what gets entered as the (numeric) taxon for a No Taxon page? I don't think beta has the quick-guide-page-add set up yet, and when I leave the taxon field blank when creating a new guide page it throws an error - maybe that's just a bug?

**Comment by clouseau** [comment]
As I think you've discovered recently, a No Taxon number is done as an increment past the current taxon. So if you are placing a No Taxon node beneath a Subspecies node (subspecies is 3500) then the first No Taxon node will be 3501, the second will be 3502, etc.

This controls where you can move No Taxon nodes when you tag a Guide Page on current BugGuide (clipboard in beta).

**Comment by kleintom** [comment]
Looking good on beta.
