### ISSUE TITLE
Can't clone the lib submodule

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#187]
I was seeing `Warning: include_once(./lib/lib_image_obfuscate.inc): failed to open stream: No such file or directory in include_once() (line 4 of /var/www/html/bugguide/images/image_obfuscate.inc).` errors, which eventually led me to think I needed to clone the lib submodule, but that's timing out:

```
klein:bugguide$ git submodule update --init --recursive
Cloning into '/tmp/bugguide/lib'...
ssh: connect to host lib.github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@lib.github.com:bugguide/lib.git' into submodule path '/tmp/bugguide/lib' failed
Failed to clone 'lib'. Retry scheduled
```
Then I tried changing `url = git@lib.github.com:bugguide/lib.git` to `url = git@github.com:bugguide/lib.git` in .gitmodule (and ran `git submodule sync`), which gave a different error:
```
klein:bugguide$ git submodule update --init --recursive
Cloning into '/tmp/bugguide/lib'...
Warning: Permanently added the RSA host key for IP address '140.82.114.3' to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:bugguide/lib.git' into submodule path '/tmp/bugguide/lib' failed
Failed to clone 'lib'. Retry scheduled
```
Does the lib repository need to be added on github?

**Comment by clouseau** [comment]
The lib repository is private, so a key will be needed. I will contact you offline.
