### ISSUE TITLE
HTML markup in links and books pages not working

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#191]
See, for example, the link page https://beta.bugguide.net/node/376224 vs https://bugguide.net/node/view/376224 where "Project Elater" is supposed to be linked
![elat_link](https://user-images.githubusercontent.com/632915/123719041-2bdac500-d846-11eb-912c-2a149e9affa6.jpg)

or the book page https://beta.bugguide.net/node/1762857 vs https://bugguide.net/node/view/1762857

**Comment by clouseau** [comment]
The citation tag at [https://bugguide.net/node/view/376224](https://bugguide.net/node/view/376224) contained an escaped left bracket:

```
&#91;cite:376224]
```

I've corrected that in current BugGuide so the citation code now works there.

The munging of the Project linking seems to be happening in the BBCode filter, I suspect.

**Comment by kleintom** [comment]
Verified as fixed on beta; browsing through books and links all of the included urls are looking good.
