### ISSUE TITLE
The links page for a taxon doesn't include a pager, so only 25 links max are viewable

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#197]
Both https://beta.bugguide.net/node/3/bglink and https://beta.bugguide.net/node/472418/bglink display 25 links, for example, even though on current bugguide each taxon lists many more links.  (Books don't seem to have that issue.)

**Comment by clouseau** [comment]
25 is the default pager number for views. This can be seen on the Links view (under Structure menu) if you have a local dev copy. The Books view seems to be set to 25 as well. To change this the number would need to change in the exported view definition here: https://github.com/bugguide/bugguide/blob/174cac2a018e3e43de800130bbb61792a7280add/sites/all/modules/custom/bglink/bglink.views_default.inc#L32

**Comment by kleintom** [comment]
I updated the title to be clearer - I think your hint helped find the issue though: it looks like the pager type for links is set to 'some', whereas the pager type for books is set to 'full'.  (And the 'some' type doesn't actually use a pager, it just displays "some" of the links: https://api.drupal.org/api/views/plugins%21views_plugin_pager_some.inc/function/views_plugin_pager_some%3A%3Ause_pager/7.x-3.x)

**Comment by kleintom** [comment]
Verified as fixed on beta - link pages now display a pager.
