### ISSUE TITLE
The "Info" tab and not the "Links" tab is highlighted when viewing a link

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#198]
See https://beta.bugguide.net/node/376238 for example.  For books, the "Books" tab is highlighted when viewing a specific book: https://beta.bugguide.net/node/2859 for example; personally I think I prefer that, but I'm not sure which is intended - seems like both should have the same behavior though.

**Comment by clouseau** [comment]
We need a section to handle nodes of type bglink after the section that handles Books, here: https://github.com/bugguide/bugguide/blob/174cac2a018e3e43de800130bbb61792a7280add/sites/all/modules/custom/bg/bg.module#L354

**Comment by kleintom** [comment]
Verified as fixed on beta (also confirmed that the similar behavior for books and images still works).
