### ISSUE TITLE
Link markup in user page biography not recognized

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#199]
I've already posted a couple of these for other areas (#183, #191) so I won't post anymore after this - maybe all will be fixed in one fell swoop?

See https://beta.bugguide.net/user/4620 where the links in the bio are wrong - oddly the links in my own bio are fine (is it an html vs bbcode issue?): https://beta.bugguide.net/user/74254

**Comment by clouseau** [comment]
The pattern of munging here is the same as in #191. A walkthrough of text processing through [https://github.com/bugguide/bugguide/tree/main/sites/all/modules/xbbcode](https://github.com/bugguide/bugguide/tree/main/sites/all/modules/xbbcode) is in order.

**Comment by kleintom** [comment]
Verified as fixed on beta; the bio page mentioned in the first comment looks good at least (the "Contributed content license terms:" url issues are a different bug), please reopen if needed.
