### ISSUE TITLE
Beta doesn't handle current bugguide's user links

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#200]
For example, current bugguide's user link is of the form https://bugguide.net/user/view/4620
but if you change that to beta by simply prefixing with beta: https://beta.bugguide.net/user/view/4620 you get a "Page not found" - the correct beta link is https://beta.bugguide.net/user/4620 (without "view").  Unless I'm just confused I think that means that links in the wild to bugguide users would fail if BG2 went live today.

(current bugguide node links, on the other hand, seem to already redirect correctly.)

**Comment by clouseau** [comment]
This is handled by Apache's mod\_rewrite. I've added a user rule to correspond with the node rule.

```
  RedirectMatch /node/view/(.*)$ https://beta.bugguide.net/node/$1
  RedirectMatch /user/view/(.*)$ https://beta.bugguide.net/user/$1
```
