### ISSUE TITLE
Remove the 'View' tab for ID Request and images in ID Request

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#205]
Visit https://beta.bugguide.net/node/6, or click on "ID Request" in the top bar and then click on the "View" tab.  Every one of the images on that page 404s to a page that says something like "The requested page "/node/1928788" could not be found."  And, indeed, if for that example I go to https://bugguide.net/node/view/1928788 it's an empty page.
![id_request](https://user-images.githubusercontent.com/632915/124342230-11775300-db88-11eb-8f16-6b8256613f43.jpg)
I was able to find the last and fourth-from-last images from their titles - they're
https://bugguide.net/node/view/1937035 and https://bugguide.net/node/view/1937049 - both were posted straight to species, never in ID Request.
Their corresponding links on that ID Request page are https://beta.bugguide.net/node/1934551 and https://beta.bugguide.net/node/1902093

The image links on https://beta.bugguide.net/id-request seem fine, but when you click on the images you see that many have been moved out of ID Request.

Could this be #160 again?

**Comment by kleintom** [comment]
I should have also said that the images on https://beta.bugguide.net/node/6 are different than the images on https://beta.bugguide.net/id-request - and I'm pretty sure the images in Recent have changed since last night when I first reported this issue, but the images in both of the id request links have not changed.

**Comment by kleintom** [comment]
So the 'View' tab here is what we would normally call the 'Info' tab on a standard guide page; I don't understand why all of those images 404, but I think in any case we don't want to show the 'View' tab on ID Request - users should only ever be on the bgimage tab for ID Request.

**Comment by kleintom** [comment]
We need to remove the View tab when you visit an image in ID Request as well; it points to node/6 (as it should).

**Comment by kleintom** [comment]
And do the same for Frass and images in Frass.

**Comment by clouseau** [comment]
Yes, something has changed to make the View tab visible when before, it was not. The if statement below the case code in bg.module that determines if tabs are viewable is responsible for the View tab; commenting out the $keep line makes the tab disappear.

I thought there was code somewhere in Drupal itself that didn't show the View tab if it was the only tab.

Anyway, you are correct, showing the View tab alone is just confusing and should not happen. Perhaps bgpage\_menu\_local\_tasks\_alter() is involved here too.

**Comment by kleintom** [comment]
Same issue at https://beta.bugguide.net/donate and https://beta.bugguide.net/help: only the View tab is visible.

**Comment by kleintom** [comment]
Looking good on beta.
