### ISSUE TITLE
Users can't edit their own comments

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#220]
See
![edit_own](https://user-images.githubusercontent.com/632915/125224814-dfef3d80-e293-11eb-80f7-8550d7cc97ca.jpg)
Users in current BugGuide can edit their comments (up to a point), so I presume we want the same here, but please close if not.

**Comment by clouseau** [comment]
I think we want to enable the permission for authenticated users and test that it's going through comment\_access(), which states

\* Authenticated users can edit their comments as long they have not been  
\* replied to. This prevents people from changing or revising their statements  
\* based on the replies to their posts.

**Comment by kleintom** [comment]
Good news: comment_access is being called;
Bad news: comment_access no longer does what its documentation says:
https://github.com/bugguide/bugguide/blob/748088e8d33f0be425312c0f3bfa62ec65447d4b/modules/comment/comment.module#L1447
As far as I can tell that just says a user can edit _any_ of their comments as long as they have the "Edit own comment" permission, and that's what I'm seeing in testing: a user can edit a comment even if someone else has already replied to it.
Looks like it was changed here: https://git.drupalcode.org/project/drupal/-/commit/fea12f8c1d4d4d71176b1a877794e1470ca2b63b - "Base comment edit links on a permission rather than a count query (performance)."

**Comment by clouseau** [comment]
Some options:

1.  Remove edit comment permissions. Once you post a comment it's immutable. Better require Preview!
2.  Accept the New Way. Anyone can go in and edit their comment, even years later.
3.  Hack core to bring back the logic removed in the commit you reference.
4.  Hack core to bring in a time-based lock. Maybe you can't edit after an hour/6 hours/a day. This keeps the performance optimization.
5.  Do it the clean way; implement hook\_comment\_view\_alter() and remove the edit link from the structured links array built in comment\_links() if the comment has been replied to.

**Comment by kleintom** [comment]
There are plenty of comments on current BugGuide of users wondering why they can't edit their comments (maybe even more wondering how to delete their comment, which they still won't be able to do), but I guess - having no idea what the actual performance impact is - I would vote to keep the current behavior, number 5; at least experienced editors and many(?) users are aware of how current comment editing works.

**Comment by kleintom** [comment]
Working as expected for authenticated users on beta, and as expected for admin locally.
