### ISSUE TITLE
Move autocomments have missing/wrong information

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#225]
I moved one of my images on beta:
![move_comment](https://user-images.githubusercontent.com/632915/126854959-2bea7795-bed5-4d60-89ba-0c6e65569cc7.jpg)

The move comment that came from current bugguide (moved by PaleoJon on May 1, 2021) has the expected information, but the move comment corresponding to the move I just did on beta July 23 has:
* jvandyk as the mover instead of me (I guess that's the hard-coded '1' here: https://github.com/bugguide/bugguide/blob/9f1627e2e2822acf6cd3a4bc0c9682977ad6999f/sites/all/modules/custom/bgimage/bgimage.pages.inc#L101)
* no "Moved from ..." information.

**Comment by clouseau** [comment]
Absolutely. That 1 should be $user->uid.

**Comment by kleintom** [comment]
The "Moved from ..." comment body, which isn't currently showing up, should also have a period at the end, as in "Moved from Ants.", in order to match the move autocomments migrated from current BugGuide (as in PaleoJon's comment above).

**Comment by kleintom** [comment]
Looks good on beta, closing as fixed.
