### ISSUE TITLE
Add ability to unlink images

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#227]
It looks like the ability to unlink a series of linked images is currently missing.
I think the button would go here: https://github.com/bugguide/bugguide/blob/7f627c6a735618ee1a2ce5c64a062b8ff094b573/sites/all/modules/custom/bgimage/bgimage.ds.field.inc#L127 next to "Add all images to clipboard",
and the bgimage_unlink_tagged callback will need to be implemented: https://github.com/bugguide/bugguide/blob/7f627c6a735618ee1a2ce5c64a062b8ff094b573/sites/all/modules/custom/bgimage/bgimage.module#L75

The 'unlink' button should only show up on the current user's images - or, I guess, if you're admin or editor or spamzapper or senioreditor?  Does current BugGuide use the 'link all bgimages' permission here?

**Comment by clouseau** [comment]
Current:

```
$bgimage = node_load($nid, "type" => "bgimage"));
if ($bgimage && (($bgimage->uid == $user->uid) || user_access("link all bgimages"))) {
  $dead_series = db_result(db_query("SELECT series FROM {bgimage_series} WHERE nid = $bgimage->nid"));
  if ($dead_series)
    db_query("DELETE FROM {bgimage_series} WHERE series = $dead_series");
  watchdog("special", "bgimage: unlinked '$dead_series'", l(t("view post"), "node/view/$dead_series"));
}
```

The db\_ calls need to be modernized but the above shows what currently happens.

**Comment by kleintom** [comment]
Looks like this is working on beta for an authenticated user, and locally for other users.
