### ISSUE TITLE
Don't show the 'move' button if the clipboard includes an image that's not yours

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#228]
I think that's the way current BugGuide works? On beta you can tag anyone's images and the 'Move' button is shown. There's a check in place so that the move will fail if you try it: https://github.com/bugguide/bugguide/blob/7f627c6a735618ee1a2ce5c64a062b8ff094b573/sites/all/modules/custom/bgimage/bgimage.pages.inc#L81 but it's weird to see the move button when you shouldn't be able to move in the first place.

(Along similar lines, it's not entirely clear to me why a user can tag someone else's images in the first place, on current BugGuide and on beta - is it because you'd need to check multiple permissions, like 'move all images' and 'link all images' for the case where those roles would be tagging images that don't belong to them?)

**Comment by clouseau** [comment]
Take a look at #12. I think the idea here was to add an image to the clipboard, and then navigate to an image that is similar, and bring up a comparison page that shows the two side-by-side.

On the one hand, it might be useful to have a universal way of taking an image and working with it, whether that's comparing images or moving or linking. On the other hand, it might lead to an array of unwanted buttons that allow you to do a bunch of things you don't normally do.

**Comment by kleintom** [comment]
Looks like this is working on beta, closing as fixed.
