### ISSUE TITLE
Image series may not be displayed in the order they were linked

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#231]
I'm having trouble reproducing on beta, but locally I have a series of two images, nodes 12 and 17:
![series](https://user-images.githubusercontent.com/632915/126878496-d64a3005-1c92-4232-b9a4-c92df4416f68.jpg)
The series is based on 17, which means 17 should be the first image of the series, and then 12. But when I go to either node 12 or 17, the "Images of this individual:" section shows 12 first, and then 17 (reverse of what's expected):
![1217](https://user-images.githubusercontent.com/632915/126878580-12b69325-09b5-46dd-8003-308ad8fa0d88.jpg)
I presume that's because the code that renders those "Images of this individual" thumbnails: https://github.com/bugguide/bugguide/blob/7f627c6a735618ee1a2ce5c64a062b8ff094b573/sites/all/modules/custom/bgimage/bgimage.ds.field.inc#L118 calls bgimage_get_series, and that function gets the nids in the series with this query:
https://github.com/bugguide/bugguide/blob/7f627c6a735618ee1a2ce5c64a062b8ff094b573/sites/all/modules/custom/bgimage/bgimage.module#L935
which if I run it locally returns
![order_wrong](https://user-images.githubusercontent.com/632915/126878699-a463d9a0-0acb-459b-9985-26b61c053a79.jpg)
in the wrong order (but the order in which the images do appear in the "Images of this individual" section). Presumably we want to order that query result by weight (but maybe percona is somehow doing what we want there, and that's why I haven't been able to reproduce on beta??).

**Comment by clouseau** [comment]
Looks to me like there's an ORDER BY weight missing in that query.

**Comment by kleintom** [comment]
I wasn't able to reproduce this on beta (I tried submitting two images, unlinked, and then linking them in the order they were submitted, and then linking two more images in the opposite order they were submitted, but the thumbnails always appeared in the correct order), but it seems to be working locally now, so closing as fixed.
