### ISSUE TITLE
Book references are (partially) sorted by title instead of by date created

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#236]
I think the intent is for book references to be sorted by Content: Post date (desc) [sorry, I don't know why there's a line through the screenshot right where you're meant to look!]
![sort_criterion](https://user-images.githubusercontent.com/632915/126922646-de770f71-377e-44b8-a8b5-767e79babc54.jpg)
but if you open the Format Settings overlay:
![wrong_default](https://user-images.githubusercontent.com/632915/126922968-0aa0f30e-59e7-4089-804b-fd5c0b420ba0.jpg)
you see that Default sort Ascending is set on the title row.
That seems to override the Content: Post date (desc) sorting setting, and indeed if I debug at https://github.com/bugguide/bugguide/blob/db121466baaa2c5a1ee797c74f15ef267939690a/sites/all/modules/custom/bgpage/bgpage.module#L614 I see the 'title asc' order by condition instead of the 'post date desc' condition.  Also if you visit, for example, https://beta.bugguide.net/node/47027/bgref?page=1, there's clearly some alphabetical title sorting going on there:
![alphabetical](https://user-images.githubusercontent.com/632915/126923160-a76a2401-89e1-41c5-9452-99eb8232bcdd.jpg)

Ahh, I actually just noticed the little arrow next to the "Title" column - I guess that's what the Format Settings overlay settings are about.  So apparently that setting overrides the Sort Criteria setting (?) and gets added to the view query as an order by condition, and then we place other order by conditions in front of that one here: https://github.com/bugguide/bugguide/blob/db121466baaa2c5a1ee797c74f15ef267939690a/sites/all/modules/custom/bgpage/bgpage.module#L650 to get the mix of order by other things followed by order by title that we see on beta:

![more_sorting](https://user-images.githubusercontent.com/632915/126923770-e011f46d-f2c6-42ee-9b18-e2bf137e1bed.jpg)
 even though the little arrow on the Title might make you think an entire column should be sorted by title, which it now isn't necessarily.

**Comment by clouseau** [comment]
Original discussion thread: [https://bugguide.net/node/view/10307](https://bugguide.net/node/view/10307)

The intent was simply to have a list of all the books at /bgref/all

The default sort on current BugGuide is by nid. That's kind of a weird default. I would expect people to either want to sort by Title or by Author, never by the nid or by the date that the book was added to BugGuide. Well, maybe people are trawling for new books here and they would show up at the bottom of /bgref/all (or the top in the case of 2.0).

Anyway, I don't feel strongly about the sort order other than people should be able to click on headings to sort, which works.

However, I do think that we should get rid of the pager. It's there by default in views but current BugGuide doesn't have it and if the intent is to look at all the books, let's show all the books, not make people page through. There are currently 6428 which is big but not unmanageable in a single page.

**Comment by kleintom** [comment]
Ah, okay, I think I was just confused about what was going on.

I've always felt confused about what I was seeing at the refs page for a given node, trying to guess which taxa the refs I was currently scrolling through were being pulled from (with no context other than the title of the refs) and not really knowing if what I was hoping to find might even be in there (basically I'd look for something in the first page or two until it seemed like I was getting colder - usually I was looking for a key for a particular taxon). I think for me personally a view more like the bgimages page would make me feel better about refs - where you get a taxon heading before the refs for that taxon (but then which taxa to show refs for and in which order becomes an issue, since I want to be able to predict what taxon is coming next, or approximately where to jump to to find a particular one). Anyway, just thinking out loud, not really making a request :-)

**Comment by kleintom** [comment]
Closing for now since the specific issue raised here seems fixed on beta - may revisit later.
