### ISSUE TITLE
Images tab not showing all images for a taxon

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#242]
As Chad Heins notes [here](https://bugguide.net/node/view/180481), when you click on the Images tab you expect to be able to page through all the images that are at that node in the tree. For example, [https://bugguide.net/node/view/1954/bgimage](https://bugguide.net/node/view/1954/bgimage) shows you all images that are directly under Araneae but no further down; they have node 1954 as their direct parent.

![](https://user-images.githubusercontent.com/456917/127417888-edb05bcd-e399-4c2b-a30a-c174e468b023.png)

However, on beta, look at the same page. It only displays some before going on to the next group:

[https://beta.bugguide.net/node/1954/bgimage](https://beta.bugguide.net/node/1954/bgimage)

![](https://user-images.githubusercontent.com/456917/127417947-7795d66b-066b-4fb3-bd28-ddf7eada9bc1.png)

**Comment by kleintom** [comment]
Hard to be 100% certain since beta and current are always in different states, but I think this is working now.
