### ISSUE TITLE
Misleading works cited hover text

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#259]
If I go to https://beta.bugguide.net/node/47027 and hover my mouse over the '2' in 'revised in(2)', I get:
![misleading](https://user-images.githubusercontent.com/632915/128441652-04b71490-a385-48ec-938c-ebf5fa980f3b.jpg)
That's (very!) misleading, since Tom Klein is the person who submitted the reference, not the person who wrote the reference. Is it important to show who submitted the reference? Or is that intended to be the person who wrote the reference?

**Comment by kleintom** [comment]
Looks like the 'by' is set here: https://github.com/bugguide/bugguide/blob/8d3d38aa5efc9f3e471a11cf7288edc0ac91d827/sites/all/modules/custom/bg/bg.module#L738-L741
I guess the issue is that you could be citing lots of different things: if you're citing an image then providing the node author seems like a helpful thing to do; if you're citing a book reference or a link or a guide page, then the node author may be misleading or not helpful. Maybe we could check the node type and decide which, if any, author to provide based on that.

**Comment by clouseau** [comment]
This is a bug, since the author of the citation (not the author of the bgref node!) is correctly shown here: https://bugguide.net/node/view/47027

**Comment by kleintom** [comment]
Working now,
