### ISSUE TITLE
Adjust submission/edit forms to match current BugGuide in layout and wording

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#262]
![image_submit](https://user-images.githubusercontent.com/632915/128448144-71a385ea-b2da-479c-ab43-5c7297176fd0.jpg)
* The state/province field and the county/parish fields are very far away, put them next to each other.
* Can we use a different description than "Location code"? To me that sounds technical and I don't know what it means until I open the dropdown menu (or read the help text...) - could we just call it 'State/Province' as in current BugGuide?
* In fact, now that I look at current BugGuide, let's duplicate its order for all the fields present in BG2, then nobody has to get used to a different order (unless there's a particular reason not to) [should probably check this for all of the submission forms?].
* The 'County/Parish/District/Region' text is partially cut off by its input box.

**Comment by kleintom** [comment]
I moved the  'County/Parish/District/Region' issue to #265 - let's make this issue about trying to match submission/edit forms to match what current BugGuide does in layout and text so that current users don't have to adapt to a new layout or different wording (unless of course there's a good reason to do so).

**Comment by clouseau** [comment]
The form as it stands is just the default form that Drupal gives us, displayed in the Bulma theme (with our subtheme).

I merged #266 but we can do so much better than our current very long form. Look at life stage with its four separate lines. Look at Date with its pointless fieldset and redundant but contradictory date formats. Much improvement is possible in layout and presentation.

**Comment by kleintom** [comment]
Order of fields and terminology (mostly) now match current Bugguide, so closing as fixed.  As expected the 'State/Province' label overflows, but that can be addressed in 273:
![state](https://user-images.githubusercontent.com/632915/129641484-96042d8d-6609-474d-8e9f-9622c03e81e5.jpg)
