### ISSUE TITLE
Location code 'Unknown' vs. 'None'

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#286]
When creating/editing an image, for 'State/Province' you can choose 'Unknown' or you can choose '-None-'; 'Unknown' is a value we added to the select, '-None-' seems to be an option that belongs to the select and not to us.  On current bugguide there's the 'Unknown' option but no 'None' option as far as I can tell.

Do we want to get rid of 'None' since we already have 'Unknown'? I can't really think of a good reason for prefering 'none' over 'unknown' (sometimes people submit images from outside our region and then 'None' would be a better description than 'Unknown', but I feel like that's not really a thing we need to support).

Bonus issue: if you set the location on an image to 'None' and then clone that image, the location on the clone is set to 'Unknown' (the default value) - if we're going to continue supporting 'None' then we should fix that.

**Comment by clouseau** [comment]
Making the field required (which it is on current) removes the -None- option.
