### ISSUE TITLE
Clipboard consistent naming

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#292]
I remembered this when reading #291, @kleintom : Since BugGuide 2.0 introduces actual tags (in the sense that you can add terms from a vocabulary to describe images) it would be nice to do a pass through the codebase and change the terminology from what used to be "tagged\_images" to "clipboard", "clipboard\_items" or similar so that the two concepts remain distinct.

We have already done this at the UI level where we have changed "tag image" to "Add to clipboard", but the code still refers to tags/tagging in bgimage.module and bgimage.pages.inc.

**Comment by kleintom** [comment]
Let's call this done since we haven't found anything that broke as a result of the renaming (not that that code has been exercised much...).
