### ISSUE TITLE
Is the contributed_images view still being used?

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#315]
I was looking at this code: https://github.com/bugguide/bugguide/blob/0b224c434958300d435149373c4771552425de91/sites/all/modules/custom/bguserfields/bguserfields.module#L36-L48
and couldn't think of where that text was showing up - I'm not sure, but it seems like maybe the contributed_images view isn't being used anymore? It was added here: https://github.com/bugguide/bugguide/commit/4f9b836f6b351661cb763d550c616c99b8de6281 but if you visit, for example, http://bugguide.test/contributed-images/2 locally you get an error (because load_user_ by_name is being passed a uid instead of a name).
I see https://github.com/bugguide/bugguide/commit/4427643168306907277cc3023e005cb22edc88de removing one contributed_images link - John, can all the contributed_images code be removed now?

**Comment by clouseau** [comment]
I think the contributed\_images view has been superseded by the my\_images view which is mapped to /user/%/images.

**Comment by kleintom** [comment]
I didn't obviously break anything with this pr, so closing as fixed.
