### ISSUE TITLE
'Undefined index: max_length' error on Create New Account page

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#320]
Visit https://beta.bugguide.net/user/register
![create_new](https://user-images.githubusercontent.com/632915/131221610-d2035f71-99b7-462e-bed9-9a45e5f8234e.jpg)
"Notice: Undefined index: max_length in text_field_widget_form() (line 514 of /var/www/html/beta.bugguide.net/bugguide/modules/field/modules/text/text.module)."

**Comment by kleintom** [comment]
Not seeing this locally at http://bugguide.test/user/register

**Comment by clouseau** [comment]
A quick look indicates that this has something to do with the email field type combined with the text widget vs the text field type combined with the text widget in bguserfields.features.field\_base.inc.

**Comment by kleintom** [comment]
Haven't seen this the past couple nights, I think this one has passed.
