### ISSUE TITLE
Only require username and email to register an account

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#325]
I guess we should show the Additional license information field on the user registration page, so that when people select 'Custom; provide details below', that field is there - here's the current page, at https://beta.bugguide.net/user/register, without that field:
![login](https://user-images.githubusercontent.com/632915/131268512-ae33b6a9-3f27-4f99-b5cb-4642e06f5e83.jpg)

**Comment by clouseau** [comment]
In reviewing this I don't like that Drupal requires that required fields be displayed on the user registration form (see "This is compulsory for 'required' fields" at /admin/config/people/accounts/fields/field\_user\_breadcrumb\_format). I understand why, but I don't like it and think we should work around it.

Current BugGuide has always been super easy to sign up for. We don't interrogate new users about licenses or how they want their breadcrumbs displayed. We set defaults and if they want to change them they can go in and change them.

We already have defaults set for the license and breadcrumb fields.

I would like the registration page to continue to be just username and email address. Super easy.

I propose that the easiest way to get there from here is to form\_alter() an \['#access'\] = FALSE into the two fields, which should preserve their requiredness, set the defaults, and make them invisible on the registration page.

**Comment by kleintom** [comment]
I totally agree; repurposing this issue.

**Comment by kleintom** [comment]
Verified as fixed on beta.
