### ISSUE TITLE
Populate date from EXIF data

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#332]
Nowadays cameras put the date taken into EXIF data.

We need to extract the data and set the date based on it. Date should still be overridable in case your camera battery went bad somewhere along the line and it has the VCR equivalent of a blinking 00:00:00.

We can do this in at least two ways.

1.  We can analyze the data during node submission. This is not very friendly because it essentially makes a Preview required.
2.  We can restore the Upload functionality that we are zapping out in [https://github.com/bugguide/bugguide/blob/84442b149f7ac03ac2e20afa39484923b768067b/sites/all/modules/custom/bgimage/bgimage.module#L654](https://github.com/bugguide/bugguide/blob/84442b149f7ac03ac2e20afa39484923b768067b/sites/all/modules/custom/bgimage/bgimage.module#L654) and if users choose to click Upload we can hook in and do autopopulation. Perhaps by wrapping the #ajax call with our own. More research is needed as to how ajax and form\_alter() would work here.

See also #254, #1.

**Comment by kleintom** [comment]
Seems to be working on beta; we can file followups if we find any issues.
