### ISSUE TITLE
Living being check for registering a new account?

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#335]
Current BugGuide has a simple check on registration: "To prove that you are a living being and not software, enter the name of this site which you can find at the upper left of this page, then an exclamation mark."
![prove](https://user-images.githubusercontent.com/632915/131766408-d102e629-dbca-423c-8103-423e59bc6b00.jpg)
Are we going to need something similar here?

**Comment by clouseau** [comment]
Yes. Bots are constantly hammering the registration form.

There are modules for this (captcha, honeypot) but I think something simple and lightweight as a form text field with instructions and a validator are fine.

**Comment by kleintom** [comment]
Working as expected on beta; closing as fixed.
