### ISSUE TITLE
The 'Works cited' section is only formatted for book references

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#347]
But a user can cite links, images, and guide pages in addition to books (keep in mind that the Works Cited is now displayed in field body sections and in comments, where some of those non-book cites are more common).

Question: do we want to display all of those types in the Works Cited section? (In my opinion we _do_ want to support #346, but that doesn't take up extra space on the page/in comments.) If we do want them all to show up in the Works Cited section then each should get its own display formatting in that section - currently only the title is displayed in Works Cited unless the work is a book.

**Comment by clouseau** [comment]
This is nice. People can always create hyperlinks by hand but this is a nice expansion of the cite functionality.

**Comment by kleintom** [comment]
Working as expected on beta:
![image](https://user-images.githubusercontent.com/632915/133711438-ced50f96-d9e7-477b-9d45-3b0a1f8ac117.png)
