### ISSUE TITLE
Don't offer the 'Edit summary' option when editing the body field

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#348]
Some of our fields are set to field type 'Long text with summary':
![summary_edit](https://user-images.githubusercontent.com/632915/132426469-c4389a5c-e446-40f3-881b-fdfe5bf5231e.jpg)
When you click on 'Edit summary' you get a summary textarea:
![summary_hide](https://user-images.githubusercontent.com/632915/132426502-3eb5441f-2e2a-4798-9822-46ca08780276.jpg)

As far as I can tell we don't have any views where the summary is being displayed (maybe [currently disabled] rss??) - were these fields intentionally set to have a summary? If not then I think we should change them to 'Long text' so that users don't wonder what the summary is all about and whether they need to fill it out etc.

**Comment by kleintom** [comment]
The fields that currently have a summary are 
* field-bgimage-body
* node-page-body
* node-bglink-body
* node-bgpage-body
* node-book-reference-body
Hmm, I'm sensing a pattern here - I guess maybe 'body' isn't our field and is auto-created with a summary? If so I think we should still try to hide the summary, if possible.

**Comment by kleintom** [comment]
Well I see the field_data_body table has a 'body_summary' column, so I'm guessing that means we're stuck with the summary type for that field. Is there anywhere that we currently display the summary?

**Comment by clouseau** [comment]
You're right, those are built-in body fields provided by core, and they come with a summary. For a bit of background see [https://www.lullabot.com/articles/replacing-the-body-field-in-drupal-8](https://www.lullabot.com/articles/replacing-the-body-field-in-drupal-8)

I agree that the summary link is confusing.

**Comment by kleintom** [comment]
bglink, bgref, bgimage, forum topic tested on beta, bgpage tested locally --> closing as fixed.
