### ISSUE TITLE
Recent images doesn't show recent books or links

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#352]
On current Bugguide, newly added book references (and links I presume) get displayed in the 'Recent' view:

![Screenshot 2021-09-09 at 20-05-00 BugGuide Net - Insects, spiders, and their kin](https://user-images.githubusercontent.com/632915/132782318-00732930-5181-4b1c-b49f-319addc23f36.png)

In new BugGuide it looks like we're not including books or links in that view:

![image](https://user-images.githubusercontent.com/632915/132782370-759b9799-96e9-4c50-811e-2599f95bd989.png)

The view is named 'Recent images', which suggests that only images are meant to be shown, but I was wondering if it was an intentional choice to not include book references (and poor links). Personally I like seeing the new references being added on current Bugguide, but maybe for the majority of users it's not of interest. Anyway, just wanted to get your thoughts here.

(I'm having trouble coming up with exactly why I like seeing the references - I think I like seeing what editors and other users are investigating and reading up on, maybe it gives a sense of vitality, that stuff is going on, progress is happening. I think it also makes things feel more accessible when references show up here (at least the full text ones), as in 'nice, if I ever need to identify X, there will be a reference', and I like feeling like people are contributing to that on the site. Plus sometimes they're of immediate interest!)

**Comment by clouseau** [comment]
Ah, I see what's going on. Those should really be two different views.

The recent images view block display is what is displayed on the home page (and through the bgactivity.module exposed as a somewhat hacky feed on [https://www.ent.iastate.edu/](https://www.ent.iastate.edu/) ) and is really about recently placed images.

The Recent tab on current BugGuide just goes to Drupal's default "hey show all the latest nodes" at /node and we could do the same thing on beta by pointing the Recent tab to /node. Or we can point it to a separate view so we have more control. But I think it is an error to point the Recent tab to the recent images view.

In response to "I want to see what is going on on BugGuide" see #26 which is a separate but interesting discussion.

**Comment by kleintom** [comment]
Working on beta.
