### ISSUE TITLE
Works cited citations should use a superscript

### ISSUE THREAD

**Issue by clouseau** [bugguide/bugguide#365]
Current BugGuide:

![](https://user-images.githubusercontent.com/456917/132967815-54407cb4-5a11-4f20-afa3-6032c90b6b9f.png)

On beta:

![](https://user-images.githubusercontent.com/456917/132967833-a0ad7249-7463-455e-aba3-7135cbc7bf06.png)

**Comment by kleintom** [comment]
Fixed on beta:
![image](https://user-images.githubusercontent.com/632915/146648646-c3ee651b-724e-48ea-aaec-0061991f5abb.png)
