### ISSUE TITLE
Image tabs on Beta don't include a 'recent images' link

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#367]
Compare https://bugguide.net/node/view/305060/bgimage vs https://beta.bugguide.net/node/305060/bgimage for example - at current BugGuide you see a 'recent images' link that takes you to a view of all the images under that node (including all descendant nodes) ordered by submission date. I think this is the view many editors use to check for new images in, say, a family they work on, so I would think this is definitely something we want? (I don't think it's there yet? I'm not seeing it.)

![image](https://user-images.githubusercontent.com/632915/132988646-5976a014-6de7-4493-9f48-3941dca01947.png)

**Comment by kleintom** [comment]
BugGuide6 implementation here: https://bitbucket.org/isubit/bugguide6/src/88f82e35f248eac41de7aa36c61ac5558bc7a1c4/sites/all/modules/bgimage/bgimage.module#lines-1188

**Comment by clouseau** [comment]
Good catch. See also #22

**Comment by kleintom** [comment]
John, should the new version of this use a solr query?

**Comment by clouseau** [comment]
I would start with an SQL query. If we see this becoming a heavy query we can optimize to Solr.

I hope to use master-replica on 2.0 so that much of the query-only load will already go to the replica (e.g., https://redcrackle.com/blog/how-use-drupal-7-mysql-master-slave-setup )

**Comment by kleintom** [comment]
Looking good on beta, though it does seem that loading the recent images for Arthropoda or Insecta is consistently taking over 10 seconds.
