### ISSUE TITLE
Allow users to cancel their votes

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#413]
Currently once a user clicks on a fivestar star, there's no way to undo their vote - they can change the number of stars, but they can't unvote.
Fivestar includes an option for allowing users to cancel their vote:
![image](https://user-images.githubusercontent.com/632915/141365123-60cd3e80-ec82-46c0-b464-1989d48226a4.png)
It adds an 'x' option to the voting area to cancel the vote:
![image](https://user-images.githubusercontent.com/632915/141365419-5c6ede9b-c19f-441d-bee5-7daa61e7203f.png)

Is there any reason to not allow that? Currently we use voting for 'photographic quality' and 'representative of taxon'.

**Comment by kleintom** [comment]
I think the reason to allow cancelling would be for accidental clicks and for anyone who clicks a star out of curiosity even though they didn't intend to cast a serious vote.

**Comment by clouseau** [comment]
I see no reason to prevent someone from cancelling their rating.

**Comment by kleintom** [comment]
Working on beta.
