### ISSUE TITLE
Error: Call to undefined function _exif_get_data_from_file_uri()

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#432]
On beta, choose an image in the 'create new image' form and then click 'Extract image data' - get an error:
![image](https://user-images.githubusercontent.com/632915/144334914-4dd1a0d6-3080-4511-84ab-f7b4156879ce.png)
Error: Call to undefined function _exif_get_data_from_file_uri() in bgimage_image_ajax_callback() (line 1134 of /var/www/html/beta.bugguide.net/bugguide/sites/all/modules/custom/bgimage/bgimage.module).

Maybe the exif module needs to be enabled on beta?

**Comment by clouseau** [comment]
Yes. Now enabled on beta, and future imports will enable exif.
