### ISSUE TITLE
Migrated bgpages are not marked as promoted

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#435]
The Recent tab on beta is intended to include new guide pages, and it does when I create a new guide page locally, but it appears that migrated guide pages are not appearing in the Recent view on beta. 

(It's kind of difficult to track that down, but for example here's a guide page created on December 9 at 7:51pm:
![image](https://user-images.githubusercontent.com/632915/145691505-cf13416f-fb58-4039-a9a5-2af46da6e99d.png)
On current BugGuide I can browse in Recent to the point where that would be if current BugGuide displayed guide pages in Recent:
![image](https://user-images.githubusercontent.com/632915/145691529-489acc99-3fe8-4729-8993-74ba2a8374f2.png)
and then find the same spot in Recent on beta:
![image](https://user-images.githubusercontent.com/632915/145691547-7a9e82f3-32f3-4861-b987-26624da08d34.png)

See https://github.com/bugguide/bugguide/pull/374/commits/07bea2a71bf1261ea4db6af80e75ec089589e0e9 for the commit that added all promoted items to Recent - I'm guessing guide pages are not being migrated as promoted, compare https://github.com/bugguide/bugguide/blob/58cf8a056e0fe4b9ab348bf510557b104c926884/sites/all/modules/custom/bgmigrate/lib/BGPageFieldMigration.inc#L89-L94

I have seen migrated book references appear in the Recent tab on beta; I haven't looked for migrated links. Newly created links and book refs do appear in Recent on beta.

**Comment by kleintom** [comment]
I'm not sure how important this issue is - it just means that when beta goes live, none of the guide pages created up to that point will show up in Recent, but all newly created ones will (judging by what I'm seeing when I add new guide pages locally) - I don't think that's really a big deal since nobody is expecting old guide pages to show up in Recent anyway (since they never did in legacy BugGuide).

**Comment by clouseau** [comment]
Confirming that Guide Pages do not have the Promoted to Front Page checkbox checked by default in current BugGuide, but they do have this checked by default in 2.0. We could check the box during migration for consistency if you think it is important so they would all be consistent.

**Comment by kleintom** [comment]
Thanks for taking a look - if there's no other reason to mark the migrated guide pages as promoted (aside from making them show up in Recent) then I think we can close this one.
