### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by SilasEckhardt** [bugguide/bugguide#460]
I don't know what's wrong, but the links in ID Request and elsewhere only show up as links in 2.0... Is that still under development? I thought I'd let you guys know in case it wasn't and you didn't know.

**Comment by clouseau** [comment]
Confirmed that solr-index is using default uri. Adding --uri option to drush solr-index. Tomorrow's build should reflect this change.

**Comment by clouseau** [comment]
This fix is now implemented and working. Thank you @SilasEckhardt
