### ISSUE TITLE
Exif date extraction isn't working

### ISSUE THREAD

**Issue by kleintom** [bugguide/bugguide#461]
Clicking 'Extract image data' on an image file with DateTime exif data doesn't update the Date field anymore (using an image that I'm pretty sure used to work).
I think in #452 we wanted to pass `drupal_realpath($file_uri)` instead of just `$file_uri` to `exif_read_data` - looks like that's what the exif module was doing internally here: https://git.drupalcode.org/project/exif/-/blob/7.x-1.x/exif.module#L260

**Comment by mbaumfalk** [comment]
I already have a fix for this in #455 with b5fca433, but we can cherry-pick that commit into a new PR if we want.

**Comment by kleintom** [comment]
Thanks Michael, I'll close this issue then.
