### ISSUE TITLE
Moving images should be on Images tab

### ISSUE THREAD

**Issue by edutrul** [bugguide/bugguide#52]
Currently moving images is allowed on the Info tab but not the Images tab. On current BugGuide you move an image by going to the Images tab and then clicking move.

### Linked issues

https://isubit.atlassian.net/browse/BUGG-173

### Comments

John:

This is still not working.

1. Enable the Image Clipboard block
2. Go to an image
3. Add to clipboard
4. Move to a different taxon
5. Click on the Images tab

What should happen: the Move button should appear.

What does happen: the Move button does not appear.

BUT the Move button appears when you are viewing and individual bgimage. This is not what we want. We want images to be movable when you are viewing the Images tab of a given taxon.

Logic for this is in bgimage.module ca. lines 802-811

**Comment by kleintom** [comment]
Working on beta (you won't see the moved image(s) in the Images tab because of #403 (they're loaded via solr), but you can see them in the Recent Images tab (which is a mysql query for now)).
