### ISSUE TITLE
Implement [thumb] filter

### ISSUE THREAD

**Issue by edutrul** [bugguide/bugguide#74]
Based on https://bitbucket.org/isubit/bugguide6/src/88f82e35f248eac41de7aa36c61ac5558bc7a1c4/sites/all/modules/bgimage/bgimage.module?at=master#bgimage.module-776, implement a filter where an image can be embedded. There is already content that uses this filter in the live site.

### Comments

Juampy:
Images are not present at Alpha yet. This is because Drupal's file stream wrappers do not support symlinks.

I have updated the logic at https://bitbucket.org/isubit/bugguide7/commits/324069a4900d4e095fe3ed6cf462fe6b09180874 so file_exists() can find images under files/raw. I will check again tomorrow.

Related Drupal core issue: https://www.drupal.org/node/1008402

Pull request https://bitbucket.org/isubit/bugguide7/pull-requests/53/master/diff adds the thumbnail filter.

![image](https://user-images.githubusercontent.com/1582129/96216847-e93abc00-0f46-11eb-953e-4d4aadf5fe3e.png)

John:

Thumbnail filter to deleted node caused  Undefined offset: 468 in _bgimage_filter_thumb_process().

**Comment by clouseau** [comment]
Closing; works as above.
